---
# vars required:
# 1. nginx_conf_tmpl
# 2. app_name

# nginx_conf_tmpl choices:
#   1. static
#   2. uwsgi

- name: install nginx
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  become: True
  with_items:
      - nginx

- name: set the nginx config file
  template: src={{ nginx_conf_tmpl }} dest={{ nginx_sites_available_path }}/{{ nginx_app_config }}
  notify: restart nginx
  become: True

- name: enable the nginx configurations
  file: >
      dest={{ nginx_sites_enabled_path }}/{{ nginx_app_config }}
      src={{ nginx_sites_available_path }}/{{ nginx_app_config }}
      state=link
  notify: restart nginx
  become: True

- name: remove the default nginx config file
  file: >
      path={{ nginx_sites_enabled_path }}/default
      state=absent
  notify: restart nginx
  become: True
