- name: deploy altaye on linode servers
  hosts: linode
  vars:
      site_name: altaye
      repo_url: git@github.com:JackonYang/altaye.org.git
      proj_path: /var/www/altaye
      nginx_conf_tmpl: roles/nginx/templates/static-nginx.conf.j2
  pre_tasks:
    - name: update the apt cache
      apt: update_cache=yes
  roles:
    - role: nginx
      domains:
        - altaye.org
        - www.altaye.org
      static_root: "{{ proj_path }}"
    - role: git
