---
- name: deploy ubuntu 16.10 on GPU
  hosts: gpu
  vars_files:
    - vars/secrets-ss.yml
  pre_tasks:
    - name: update the apt cache
      apt: update_cache=yes cache_valid_time=3600
      sudo: True
  roles:
    - role: common
    - role: update_ddns
      host_name: "{{ gpu_host_name }}"
