#!/usr/bin/env ansible-playbook
---
- name: deploy jackon.me
  hosts: linode
  vars:
      proj_name: jackon-me
      repo_url: git@github.com:JackonYang/jackon.me.git
      venv_path: /var/www/{{ proj_name }}
      project_dirname: project
      proj_path: "{{ venv_path }}/{{ project_dirname }}"
      static_root: "{{ venv_path }}/deploy"
  pre_tasks:
    - name: update the apt cache
      apt: update_cache=yes cache_valid_time=3600
      become: True
  roles:
    - role: nginx
      domains:
        - jackon.me
        - www.jackon.me
      app_name: "{{ proj_name }}"
      nginx_conf_tmpl: static-nginx.conf.j2
      static_root: "{{ venv_path }}/deploy"
    - role: clone_code
      # repo_url
      # proj_path
    - role: pelican
      debug_path: "{{ proj_path }}/output"
