#!/usr/bin/env ansible-playbook
---
- name: deploy altaye.org
  hosts: linode
  vars:
      proj_name: altaye-org
      repo_url: git@github.com:JackonYang/altaye.org.git
      proj_path: /var/www/altaye
  pre_tasks:
    - name: update the apt cache
      apt: update_cache=yes cache_valid_time=3600
      become: True
  roles:
    - role: nginx
      domains:
        - altaye.org
        - www.altaye.org
      app_name: "{{ proj_name }}"
      nginx_conf_tmpl: static-nginx.conf.j2
      static_root: "{{ proj_path }}"
    - role: git
