#!/usr/bin/env ansible-playbook
---
- name: deploy jackon.me
  hosts: jackon.me
  vars:
      proj_name: jackon-me
      repo_url: git@github.com:JackonYang/jackon.me.git
      project_root: /var/www/{{ proj_name }}
      src_path: "{{ project_root }}/src"
      prod_path: "{{ project_root }}/prod"

  pre_tasks:
    - name: update the apt cache
      apt: update_cache=yes cache_valid_time=3600
      become: True

  roles:

    - role: nginx
      domains:
        - jackon.me
        - www.jackon.me
      app_name: "{{ proj_name }}"
      nginx_conf_tmpl: static-nginx.conf.j2
      static_root: "{{ prod_path }}"

    - role: docker
    - role: clone_code
      # repo_url
      # src_path

    - role: pelican
      debug_path: "{{ src_path }}/output"
      venv_path: "{{ project_root }}"
      # src_path
      # prod_path
