---
- name: deploy ubuntu 14.04
  hosts: jackon.me
  vars_files:
    - vars/secrets-ss.yml
  pre_tasks:

    - name: update the apt cache
      apt: update_cache=yes cache_valid_time=3600
      become: True

    - name: install apt packages
      apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
      become: True
      with_items:
        - git
        - vim

  roles:
    - role: docker
    - role: python-env

    - role: nginx  # JRIA proxy
      domains:
        - jira.jackon.me
      app_name: "jira"
      nginx_conf_tmpl: port-forwarding-nginx.conf.j2
      root_uri: "http://127.0.0.1:8080"
