---
- name: Install pelican
  pip: name={{ item }} virtualenv={{ venv_path }}
  with_items:
    - pelican
    - Markdown


- name: clean debug_path
  file: path={{ debug_path }} state=absent


- name: generate the site with pelican
  command: "pelican {{ src_path }}/content -o {{ debug_path }}"
  args:
    chdir: "{{ src_path }}"
  environment:
    PATH: "{{ venv_path }}/bin"


- name: clean prod_path
  file: path={{ prod_path }} state=absent


- name: deploy to prod_path
  command: "cp -R {{ debug_path }} {{ prod_path }}"
