---
- name: Install pelican
  make:
    chdir: "{{ src_path }}"
    target: build
  environment:
    PYTHONPATH: /usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages


- name: clean debug_path
  file: path={{ debug_path }} state=absent


- name: generate the site with pelican
  make:
    chdir: "{{ src_path }}"
    target: generate
  environment:
    PYTHONPATH: /usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages


- name: clean prod_path
  file: path={{ prod_path }} state=absent


- name: deploy to prod_path
  command: "cp -R {{ debug_path }} {{ prod_path }}"
