---
- name: install apt packages
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  sudo: True
  with_items:
    - python-pip
    - python-virtualenv
    - git
    - vim


- name: upgrade pip
  pip:
    name: pip
    extra_args: --upgrade
  sudo: True


# create a ~/.pip if it doesn't exist
- file:
    path: "{{ ansible_env.HOME }}/.pip"
    state: directory


- name: Generate pip.conf
  template: src=pip.conf.j2
            dest="{{ ansible_env.HOME }}/.pip/pip.conf"
